origin $00082000
texto_01:
dialogue_text("                                    ")
dialogue_text("LADEN: Gyra!!!                      ")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("LADEN: Agora é hora de acabar com   ")
dialogue_text("suas atrocidades, eu irei por um    ")
dialogue_text("fim nisso tudo.                     ")
dialogue_text("                                    ")
dialogue_text("GYRA: Ha ha ha... Você é ambicioso  ")
dialogue_text("mas você nunca irá me derrotar...   ")
dialogue_text("LADEN: CHEGA, VAMOS LUTAR!!!        ")
dialogue_text("GYRA: Antes eu tenho uma pequena    ")
dialogue_text("surpresa para você. Olhe bem para   ")
dialogue_text("o meu rosto.                        ")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("LADEN: Eu não posso acreditar!!!    ")
dialogue_text("GYRA: A quanto tempo, Laden.        ")
dialogue_text("LADEN: Você, você, é impossível.    ")
dialogue_text("Você realmente é ele, Roki?         ")
dialogue_text("GYRA: Isso mesmo, Laden. Seu irmão  ")
dialogue_text("Roki, entrou em uma outra dimensão  ")
dialogue_text("e se tornou um novo ser,            ")
dialogue_text("Gyra, o Senhor das trevas.          ")
dialogue_text("LADEN: Não, isso não pode ser       ")
dialogue_text("verdade!!!                          ")
dialogue_text("                                    ")
dialogue_text("GYRA: Junte-se a  mim. Juntos iremos")
dialogue_text("conquistar esse mundo patético.     ")
dialogue_text("LADEN: Isso nunca irá acontecer.    ")
dialogue_text("GYRA: Tolos serão aqueles que       ")
dialogue_text("tentarão me deter.                  ")
dialogue_text("LADEN: Então foi isso o que         ")
dialogue_text("realmente aconteceu com o meu irmão?")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("GYRA: Clauss, Salome, venham até    ")
dialogue_text("aqui.                               ")
dialogue_text("                                    ")
dialogue_text("CLAUSS: Meu senhor, estamos prontos ")
dialogue_text("para executar suas ordens de        ")
dialogue_text("capturar o Rei Lerelei.             ")
dialogue_text("                                    ")
dialogue_text("SALOME: E também de capturarmos o   ")
dialogue_text("ELEMENTAL.                          ")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("GYRA: Tudo está indo conforme meus  ")
dialogue_text("planos. Não há como voltar          ")
dialogue_text("atrás agora.                        ")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("CLAUSS: Entendido, meu senhor.      ")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("SALOME: Vamos obedecer suas ordens, ")
dialogue_text("meu senhor.                         ")
dialogue_text("                                    ")
dialogue_text("GYRA: Não vou perder mais tempo com ")
dialogue_text("você. Nos veremos em breve...       ")
dialogue_text("Isso se você ficar vivo ate lá.     ")
dialogue_text("LADEN: Roki, por favor, espere!     ")
dialogue_text("GYRA: Ha ha ha ha ha.......         ")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("LADEN: Roki, por que, por que?      ")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("NEENA: Você me salvou! Obrigada.    ")
dialogue_text("LADEN: Quem é você?                 ")
dialogue_text("NEENA: Meu nome é Neena. Eu sirvo ao")
dialogue_text("ELEMENTAL, mas eu fui capturada.    ")
dialogue_text("LADEN: Você está salva agora.       ")
dialogue_text("Já pode retornar ao seu povo.       ")
dialogue_text("NEENA: Não. Você me salvou, tenho   ")
dialogue_text("uma divida de gratidão agora.       ")
dialogue_text("LADEN: é muito perigoso para você.  ")
dialogue_text("NEENA: é meu dever agora ajudá-lo.  ")
dialogue_text("Mesmo que seja algo muito perigoso. ")
dialogue_text("LADEN: Ei, espere!                   ")
dialogue_text("                                    ")
dialogue_text("                                    ")
origin $00082C50
texto_02:
break_line()
dialogue_text("NEENA: Era você quem eu estava      ")
dialogue_text("procurando, esse tempo todo.        ")
dialogue_text("LADEN: Quem é você?                 ")
dialogue_text("NEENA: Eu sou a reencarnação do     ")
dialogue_text("lendário anel. O anel com a         ")
dialogue_text("capacidade de canalizar o poder     ")
dialogue_text("de todos os Elementais.             ")
dialogue_text("LADEN: Então é você.                ")
dialogue_text("NEENA: Sim. Eu estive testando você.")
dialogue_text("Precisava saber se você era         ")
dialogue_text("realmente digno.                    ")
dialogue_text("NEENA: Seus inimigos são bem        ")
dialogue_text("poderosos. Clauss e Salome, são     ")
dialogue_text("protegidos pelo poder das Trevas.   ")
dialogue_text("Somente com o poder da luz, você    ")
dialogue_text("conseguirá derrotá-los.             ")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("NEENA: Coloque-me em seu dedo.      ")
dialogue_text("Eu posso lhe dar o poder dos        ")
dialogue_text("Elementais.                         ")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("LADEN: Neena.                       ")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("LADEN: Roki!                        ")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("ROKI: Você ficou mais forte desde   ")
dialogue_text("que nos conhecemos.                 ")
dialogue_text("LADEN: O que houve com você,        ")
dialogue_text("meu irmão? Me diga!!!               ")
dialogue_text("ROKI: Eu me enganei por várias vezes")
dialogue_text("Pensava que o poder das Trevas      ")
dialogue_text("poderia me tornar invencível.       ")
dialogue_text("Quando soube que este poder estava  ")
dialogue_text("selado em uma caverna abaixo da     ")
dialogue_text("nossa cidade, então eu fui atrás    ")
dialogue_text("dele. Eu achei o poder das Trevas   ")
dialogue_text("mas quando eu libertei suas forças, ")
dialogue_text("eu fui possuído pelo espirito       ")
dialogue_text("do demonio o Rei Gyra.        ")
dialogue_text("                         ")
origin $000832D8
texto_03:
break_line()
dialogue_text("LADEN: ....                         ")
dialogue_text("ROKI: Vejo agora que o Rei Gyra era ")
dialogue_text("apenas o reflexo da maldade que     ")
dialogue_text("havia dentro de mim. Eu dei vida    ")
dialogue_text("a esse monstro, o Rei Gyra.         ")
dialogue_text("LADEN: Isso não é verdade, em seu   ")
dialogue_text("coração so existe bondade!           ")
origin $000833E2
texto_03:
break_line()
dialogue_text("ROKI: LADEN.......                  ")
dialogue_text("LADEN: NAO!                         ")
dialogue_text("ROKI: Meus olhos, tudo está ficando ")
dialogue_text("escuro agora. Essa é a hora de eu   ")
dialogue_text("partir deste mundo. Adeus meu irmão.")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("LADEN: Roki! Roki!! Não morra agora!")
dialogue_text("                                    ")
dialogue_text("                                    ")
origin $0008355E
break_line()
dialogue_text("O Rei Lorelei foi libertado.        ")
dialogue_text("Os demonios seguidores do Rei Gyra  ")
dialogue_text("nunca mais foram vistos novamente.  ")
dialogue_text("mas...                              ")
dialogue_text("                                    ")
dialogue_text("Laden...                            ")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("Equipe de Introdução                ")
dialogue_text("                                    ")
dialogue_text("Diretor de Programação              ")
dialogue_text("                      ASOBI-NIN     ")
dialogue_text("Programador Assistente              ")
dialogue_text("                      GAN-CHAN      ")
dialogue_text("Diretor de Arte - Plano de fundo    ")
dialogue_text("                      ARMY          ")
dialogue_text("Diretor de Arte - Desenho inimigos  ")
dialogue_text("                      MUTON         ")
dialogue_text("Efeitos de som                      ")
dialogue_text("                      MATAI         ")
dialogue_text("Efeitos de som                      ")
dialogue_text("                      SU-ROUNIN     ")
dialogue_text("Produtora                           ")
dialogue_text("                      T.O           ")
dialogue_text("Tradução Carnage VERSAO BETA        ")
dialogue_text("                                    ")
dialogue_text("                                    ")
dialogue_text("")
dialogue_text("")
    db $1A
    end()
    end()
    end()
